services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:80"
    volumes:
      - ./backend/api/:/var/www/html
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: sakura46
      POSTGRES_USER: ryuta
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
